### ISSUE TITLE
Stress ball functionality

### ISSUE THREAD

**Issue by r4c3** [eatcode-gt/eatcodeweb#25]

**Comment by Giovanni1014** [comment]
what is this actually?

**Comment by r4c3** [comment]
> what is this actually?

honestly great question. Was thinking your cursor turns to a boxing glove and you punch the button and it recoils or sum. Deleted it on my branch doe

**Comment by Giovanni1014** [comment]
interesting, maybe we can implement that later on

**Comment by r4c3** [comment]
^^either delete or add functionality by demo

**Comment by Giovanni1014** [comment]
delete for now

**Comment by Giovanni1014** [comment]
"see solution" at least after demo
