### ISSUE TITLE
Potential incorrect usage of createContext and useContext

### ISSUE THREAD

**Issue by Giovanni1014** [eatcode-gt/eatcodeweb#29]
https://github.com/eatcode-gt/eatcodeweb/blob/1d26a6ea3d338ff81537ae4a62ae8c66bedc07f8/frontend/src/pages/create.js#L49

There's multiple "UserContext" declared, one in create.js and one in question.js. According to [https://beta.reactjs.org/apis/react/createContext](url), I think we should declare it in one file and import it when we need it. Also, I don't think we need to pass it to children components, instead, as what the article shows, we could import it and use it.
Correct me if I'm wrong.
The only reason I'm using this instead of messaging is that this is so cool

<img width="812" alt="Screen Shot 2022-11-17 at 7 42 25 PM" src="https://user-images.githubusercontent.com/46436786/202590284-931de6ad-0d43-4a85-9d2d-db875cc28dbc.png">

**Comment by Giovanni1014** [comment]
@aaronliuo

**Comment by aaronliuo** [comment]
Yes I agree, I will change this on my next pull request.
